Begin implementing locked pipeline launching

diff --git a/hooks/post-checkout b/hooks/post-checkout
--- a/hooks/post-checkout
+++ b/hooks/post-checkout
@@ -15,8 +15,15 @@ fi
 # If we think we are authorized, let's check to make sure that our secret keys are actually valid
 PRIVATE_KEY_PATH=$(mktemp)
 base64dec <<<"${BUILDKITE_PLUGIN_CRYPTIC_BASE64_AGENT_PRIVATE_KEY_SECRET}" >"${PRIVATE_KEY_PATH}"
+if ! is_rsa_private_key "${PRIVATE_KEY_PATH}"; then
+    die "Invalid RSA private key passed from agent environment hook!"
+fi
+
 PUBLIC_KEY_PATH=$(mktemp)
 base64dec <<<"${BUILDKITE_PLUGIN_CRYPTIC_BASE64_AGENT_PUBLIC_KEY_SECRET}" >"${PUBLIC_KEY_PATH}"
+if ! is_rsa_private_key "${PRIVATE_KEY_PATH}"; then
+    die "Invalid RSA private key passed from agent environment hook!"
+fi
 
 # Search for repository key based off of the private key fingerprint
 RSA_FINGERPRINT=$(rsa_fingerprint "${PRIVATE_KEY_PATH}")
@@ -59,5 +66,8 @@ for PAIR in "${ENCRYPTED_VARIABLES[@]}"; do
     export "${VARNAME}"="${VALUE}"
 done
 
+# Sign the initial buildkite job ID, for future launch needs
+export BUILDKITE_PLUGIN_CRYPTIC_SIGNED_JOB_ID_BASE64=$(echo "${BUILDKITE_INITIAL_JOB_ID}" | sign_rsa "${PUBLIC_KEY_PATH}" | base64enc)
+
 # Clean up public/private key paths
-rm -f "${PRIVATE_KEY_PATH}" "${PUBLIC_KEY_PATH}" "${UNENCRYPTED_REPO_KEY_PATH}"
+shred -u "${PRIVATE_KEY_PATH}" "${PUBLIC_KEY_PATH}" "${UNENCRYPTED_REPO_KEY_PATH}"
