Slight cleanup

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -75,7 +75,6 @@ for PIPELINE_IDX in "${!SIGNED_PIPELINES[@]}"; do
     fi
     if [[ "$(decrypt_aes "${UNENCRYPTED_REPO_KEY_PATH}" <"${SIGNATURE_FILE}")" != "${FULL_TREEHASH}" ]]; then
         SIGNATURE_FAIL_MSG="Pipeline '${PIPELINE_PATH}' fails treehash signature check!  You may need to re-run cryptic/bin/sign_treehashes!"
-        echo "${SIGNATURE_FAIL_MSG}" >&2
 
         HASH_OVERRIDE_VAR="BUILDKITE_PLUGIN_CRYPTIC_SIGNED_PIPELINES_${PIPELINE_IDX}_ALLOW_HASH_OVERRIDE"
         if [[ -v "${HASH_OVERRIDE_VAR}" ]] && [[ "${!HASH_OVERRIDE_VAR}" == "true" ]]; then
@@ -103,7 +102,7 @@ for PIPELINE_IDX in "${!SIGNED_PIPELINES[@]}"; do
         else
             # Execute `die` in a subshell so that we can print out failure messages for each pipeline,
             # then fail out once at the end, ignoring the `exit` and failure that it creates.
-            (die "Refusing to continue execution; pipeline '${PIPELINE_PATH}' fails treehash signature check!  You may need to re-run cryptic/bin/sign_treehashes!"; ) || true
+            (die "${SIGNATURE_FAIL_MSG}"; ) || true
             SHOULD_FAIL=true
             continue
         fi
